import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Banknote, CalendarClock, CheckCircle2, Clock3, MapPin, RefreshCw, ShieldCheck, Star, Wrench } from "lucide-react";
import { toast } from "sonner";
import { ServiceShell } from "@/components/service/ServiceShell";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";

const LABELS: Record<string, string> = {
  new: "بانتظار عروض المزودين", accepted: "تم اختيار المزود", arrived: "وصل المزود", in_progress: "العمل جارٍ",
  waiting_payment: "بانتظار تسجيل الدفع", waiting_confirmation: "بانتظار تأكيدك", completed: "مكتمل", cancelled: "ملغي",
  inactive: "متوقف مؤقتًا", warranty_requested: "طلب الضمان مفتوح", warranty_in_progress: "معالجة الضمان",
  warranty_waiting_confirmation: "بانتظار تأكيد حل الضمان", warranty_resolved: "تم حل الضمان", warranty_rejected: "الضمان مرفوض",
};

export function CustomerRequestsPage() {
  const { user } = useAuth(); const client = useQueryClient(); const [warrantyReason, setWarrantyReason] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["customer-maintenance-requests", user?.id], enabled: !!user, queryFn: async () => {
    const { data, error } = await (supabase as any).from("maintenance_requests").select("id,ref_no,title,description,status,service_code,priority,offered_price,after_service_policy,service_timing_mode,scheduled_date,scheduled_time,location_note,created_at,updated_at,original_completed_at,customer_addresses(city,district,street,building_no,unit_no),service_catalog(name_ar,family_code),maintenance_providers(name,rating,rating_count),provider_offers(id,status,offered_price,notes,quoted_at,maintenance_providers(name,rating,rating_count)),provider_invoices(id,status,amount,base_amount,vat_amount,payment_method)").eq("user_id", user!.id).order("created_at", { ascending: false });
    if (error) throw error; return data as any[];
  } });
  useEffect(() => { if (!user) return; const channel = supabase.channel(`customer-work-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "maintenance_requests", filter: `user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["customer-maintenance-requests", user.id] })).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [user, client]);

  const command = useMutation({ mutationFn: async ({ kind, requestId, value }: { kind: "accept" | "confirm" | "pay" | "warranty" | "resolve"; requestId: string; value?: string }) => {
    const request = (query.data ?? []).find((item) => item.id === requestId); if (!request) throw new Error("الطلب غير موجود");
    if (kind === "accept") { const { error } = await (supabase as any).rpc("accept_provider_offer", { offer_id_input: value, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "confirm") { const { error } = await (supabase as any).rpc("confirm_maintenance_work", { request_id_input: requestId, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "pay") { const invoice = request.provider_invoices?.[0]; const { error } = await (supabase as any).rpc("submit_maintenance_payment", { invoice_id_input: invoice?.id, payment_method_input: "cash" }); if (error) throw error; }
    if (kind === "warranty") { const { error } = await (supabase as any).rpc("open_maintenance_warranty", { request_id_input: requestId, reason_input: value, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "resolve") { const { error } = await (supabase as any).rpc("transition_maintenance_request", { request_id_input: requestId, expected_status_input: "warranty_waiting_confirmation", target_status_input: "warranty_resolved", idempotency_key_input: crypto.randomUUID(), payload_input: {} }); if (error) throw error; }
  }, onSuccess: async () => { await query.refetch(); toast.success("تم حفظ الإجراء في سجل الطلب"); }, onError: (error: Error) => toast.error(error.message) });

  const requests = query.data ?? [];
  return <ServiceShell><div className="flex items-end justify-between"><div><p className="text-[10px] font-black text-primary">مركز المتابعة</p><h1 className="text-2xl font-black">طلباتي</h1><p className="mt-1 text-[10px] text-muted-foreground">العرض والتنفيذ والدفع والضمان في مسار واحد موثّق.</p></div><Button variant="outline" size="sm" onClick={() => query.refetch()}><RefreshCw className="ml-2 h-4 w-4" />تحديث</Button></div>
    {query.isLoading ? <div className="mt-6 grid gap-3">{[1,2,3].map((item) => <div key={item} className="h-36 animate-pulse rounded-3xl bg-muted" />)}</div> : requests.length === 0 ? <div className="mt-8 rounded-[28px] border border-dashed bg-white p-10 text-center"><Wrench className="mx-auto h-8 w-8 text-primary" /><h2 className="mt-3 font-black">لا توجد طلبات بعد</h2><p className="mt-1 text-[10px] text-muted-foreground">اختر خدمة وأرسل طلبك الأول.</p><Button asChild className="mt-5 rounded-xl"><a href="/request/new">ابدأ طلبًا</a></Button></div> : <div className="mt-6 grid gap-4">{requests.map((request) => {
      const address = request.customer_addresses; const offers = (request.provider_offers ?? []).filter((offer: any) => offer.status === "pending" && offer.quoted_at && offer.offered_price); const invoice = request.provider_invoices?.[0];
      return <article key={request.id} className="rounded-[24px] border border-[#e5e2d9] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] font-black text-primary">طلب #{request.ref_no}</span><h2 className="mt-1 text-[14px] font-black">{request.title}</h2><p className="mt-1 text-[9px] text-muted-foreground">{request.service_catalog?.name_ar ?? request.service_code}</p></div><span className="rounded-full bg-primary/10 px-3 py-1.5 text-[9px] font-black text-primary">{LABELS[request.status] ?? request.status}</span></div><p className="mt-3 line-clamp-2 text-[10px] leading-5 text-muted-foreground">{request.description}</p><div className="mt-4 grid gap-2 border-t pt-3 text-[9px] text-muted-foreground"><span><MapPin className="ml-1 inline h-3.5 w-3.5 text-primary" />{address?.city} · {address?.district}</span><span><CalendarClock className="ml-1 inline h-3.5 w-3.5 text-primary" />{request.service_timing_mode === "asap" ? "في أسرع وقت" : `${request.scheduled_date} · ${request.scheduled_time}`}</span><span>{request.status === "completed" ? <CheckCircle2 className="ml-1 inline h-3.5 w-3.5 text-primary" /> : <Clock3 className="ml-1 inline h-3.5 w-3.5 text-primary" />}آخر تحديث: {new Date(request.updated_at).toLocaleString("ar-SA")}</span></div>
        {request.status === "new" && offers.length > 0 && <div className="mt-4 rounded-2xl bg-[#f7f5ee] p-3"><p className="text-[10px] font-black">العروض المتاحة ({offers.length})</p><div className="mt-2 grid gap-2 md:grid-cols-2">{offers.map((offer: any) => <div key={offer.id} className="rounded-xl border bg-white p-3"><div className="flex items-center justify-between"><strong className="text-[10px]">{offer.maintenance_providers?.name}</strong><span className="text-[9px] text-amber-600"><Star className="inline h-3 w-3 fill-current" /> {offer.maintenance_providers?.rating ?? "جديد"}</span></div><strong className="mt-2 block text-lg text-primary">{Number(offer.offered_price).toLocaleString("ar-SA")} ر.س</strong><p className="mt-1 text-[8px] text-muted-foreground">قبل ضريبة القيمة المضافة</p>{offer.notes && <p className="mt-2 text-[9px] leading-5 text-muted-foreground">{offer.notes}</p>}<Button disabled={command.isPending} onClick={() => command.mutate({ kind: "accept", requestId: request.id, value: offer.id })} className="mt-3 w-full rounded-xl">اختيار هذا المزود</Button></div>)}</div></div>}
        {request.status === "waiting_confirmation" && <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "confirm", requestId: request.id })} className="mt-4 w-full rounded-xl"><CheckCircle2 className="ml-2 h-4 w-4" />تأكيد جودة التنفيذ وإصدار الفاتورة</Button>}
        {request.status === "waiting_payment" && invoice && <div className="mt-4 rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black">الفاتورة</p><small className="text-[8px] text-muted-foreground">الأساس {invoice.base_amount} + الضريبة {invoice.vat_amount}</small></div><strong className="text-xl text-primary">{Number(invoice.amount).toLocaleString("ar-SA")} ر.س</strong></div>{invoice.status === "pending_payment" ? <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "pay", requestId: request.id })} className="mt-3 w-full rounded-xl"><Banknote className="ml-2 h-4 w-4" />تسجيل الدفع النقدي</Button> : <p className="mt-3 rounded-xl bg-amber-100 p-3 text-center text-[9px] font-black text-amber-800">تم تسجيل الدفع، بانتظار تأكيد المزود</p>}</div>}
        {request.status === "completed" && request.after_service_policy !== "none" && <div className="mt-4 rounded-2xl border border-dashed p-3"><p className="flex items-center gap-2 text-[10px] font-black"><ShieldCheck className="h-4 w-4 text-primary" />خدمة ما بعد التنفيذ: {request.after_service_policy}</p><Textarea rows={2} value={warrantyReason[request.id] ?? ""} onChange={(event) => setWarrantyReason((current) => ({ ...current, [request.id]: event.target.value }))} placeholder="اشرح المشكلة التي ظهرت بعد التنفيذ" className="mt-2" /><Button variant="outline" disabled={(warrantyReason[request.id]?.trim().length ?? 0) < 5 || command.isPending} onClick={() => command.mutate({ kind: "warranty", requestId: request.id, value: warrantyReason[request.id] })} className="mt-2 w-full rounded-xl">فتح طلب الضمان</Button></div>}
        {request.status === "warranty_waiting_confirmation" && <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "resolve", requestId: request.id })} className="mt-4 w-full rounded-xl">تأكيد حل مشكلة الضمان</Button>}
      </article>;
    })}</div>}
  </ServiceShell>;
}
