import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Banknote, CalendarClock, CheckCircle2, Clock3, MapPin, RefreshCw, ShieldCheck, Star, Wrench, XCircle } from "lucide-react";
import { toast } from "sonner";
import { ServiceShell } from "@/components/service/ServiceShell";
import { EmptyState, PageHeading, StatusBadge } from "@/components/service/ServiceUI";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { canCustomerCancel, canCustomerReschedule, isTerminalMaintenanceStatus } from "@/lib/maintenanceWorkflow";

export function CustomerRequestsPage() {
  const { user } = useAuth(); const client = useQueryClient(); const [warrantyReason, setWarrantyReason] = useState<Record<string, string>>({});
  const [filter, setFilter] = useState<"active" | "completed" | "all">("active");
  const [manageRequestId, setManageRequestId] = useState<string | null>(null);
  const [scheduleDate, setScheduleDate] = useState(""); const [scheduleTime, setScheduleTime] = useState(""); const [changeReason, setChangeReason] = useState("");
  const query = useQuery({ queryKey: ["customer-maintenance-requests", user?.id], enabled: !!user, queryFn: async () => {
    const { data, error } = await (supabase as any).from("maintenance_requests").select("id,ref_no,title,description,status,service_code,priority,offered_price,after_service_policy,service_timing_mode,scheduled_date,scheduled_time,location_note,created_at,updated_at,original_completed_at,customer_addresses(city,district,street,building_no,unit_no),service_catalog(name_ar,family_code),maintenance_providers(name,rating,rating_count),provider_offers(id,status,offered_price,notes,quoted_at,maintenance_providers(name,rating,rating_count)),provider_invoices(id,status,amount,base_amount,vat_amount,payment_method)").eq("user_id", user!.id).order("created_at", { ascending: false });
    if (error) throw error; return data as any[];
  } });
  useEffect(() => { if (!user) return; const channel = supabase.channel(`customer-work-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "maintenance_requests", filter: `user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["customer-maintenance-requests", user.id] })).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [user, client]);

  const command = useMutation({ mutationFn: async ({ kind, requestId, value }: { kind: "accept" | "confirm" | "pay" | "warranty" | "resolve" | "cancel" | "reschedule"; requestId: string; value?: string }) => {
    const request = (query.data ?? []).find((item) => item.id === requestId); if (!request) throw new Error("الطلب غير موجود");
    if (kind === "accept") { const { error } = await (supabase as any).rpc("accept_provider_offer", { offer_id_input: value, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "confirm") { const { error } = await (supabase as any).rpc("confirm_maintenance_work", { request_id_input: requestId, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "pay") { const invoice = request.provider_invoices?.[0]; const { error } = await (supabase as any).rpc("submit_maintenance_payment", { invoice_id_input: invoice?.id, payment_method_input: "cash" }); if (error) throw error; }
    if (kind === "warranty") { const { error } = await (supabase as any).rpc("open_maintenance_warranty", { request_id_input: requestId, reason_input: value, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "resolve") { const { error } = await (supabase as any).rpc("transition_maintenance_request", { request_id_input: requestId, expected_status_input: "warranty_waiting_confirmation", target_status_input: "warranty_resolved", idempotency_key_input: crypto.randomUUID(), payload_input: {} }); if (error) throw error; }
    if (kind === "cancel") { const { error } = await (supabase as any).rpc("cancel_maintenance_request", { request_id_input: requestId, reason_input: value, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
    if (kind === "reschedule") { const { error } = await (supabase as any).rpc("reschedule_maintenance_request", { request_id_input: requestId, scheduled_date_input: scheduleDate, scheduled_time_input: scheduleTime, reason_input: value || null, idempotency_key_input: crypto.randomUUID() }); if (error) throw error; }
  }, onSuccess: async () => { setManageRequestId(null); setChangeReason(""); setScheduleDate(""); setScheduleTime(""); await query.refetch(); toast.success("تم حفظ الإجراء في سجل الطلب"); }, onError: (error: Error) => {
    const messages: Record<string, string> = { valid_cancellation_reason_required: "اكتب سبب الإلغاء بوضوح", cancellation_requires_support: "بعد اختيار المزود يلزم التواصل مع الدعم للإلغاء", schedule_must_be_future: "اختر موعدًا حاليًا أو لاحقًا", reschedule_not_allowed: "لا يمكن إعادة الجدولة في الحالة الحالية" };
    toast.error(messages[error.message] ?? error.message);
  } });

  const requests = query.data ?? [];
  const visibleRequests = requests.filter((request) => filter === "all" || (filter === "completed" ? isTerminalMaintenanceStatus(request.status) : !isTerminalMaintenanceStatus(request.status)));
  return <ServiceShell><PageHeading eyebrow="مركز المتابعة" title="طلباتك" description="قارن العروض، تابع التنفيذ، وأدر الدفع والضمان من سجل موحد." action={<Button variant="outline" size="sm" onClick={() => query.refetch()}><RefreshCw className="ml-2 h-4 w-4" />تحديث</Button>} />
    <div className="mt-6 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="تصفية الطلبات">{([['active','النشطة'],['completed','المكتملة'],['all','الكل']] as const).map(([value,label]) => <button key={value} role="tab" aria-selected={filter === value} onClick={() => setFilter(value)} className={`min-h-11 shrink-0 rounded-full px-5 text-sm font-black ${filter === value ? "bg-primary text-white" : "border bg-white text-muted-foreground"}`}>{label}</button>)}</div>
    {query.isLoading ? <div className="mt-6 grid gap-3">{[1,2,3].map((item) => <div key={item} className="h-40 animate-pulse rounded-3xl bg-muted" />)}</div> : requests.length === 0 ? <div className="mt-8"><EmptyState icon={Wrench} title="لا توجد طلبات بعد" description="اختر خدمة وأرسل طلبك الأول، ويمكنك متابعة كل خطوة من هنا." action={<Button asChild className="rounded-xl"><a href="/request/new">ابدأ طلبًا</a></Button>} /></div> : visibleRequests.length === 0 ? <div className="mt-8"><EmptyState title="لا توجد طلبات في هذا القسم" description="غيّر عامل التصفية لعرض بقية طلباتك." /></div> : <div className="mt-6 grid gap-4">{visibleRequests.map((request) => {
      const address = request.customer_addresses; const offers = (request.provider_offers ?? []).filter((offer: any) => offer.status === "pending" && offer.quoted_at && offer.offered_price); const invoice = request.provider_invoices?.[0];
      return <article key={request.id} className="service-panel p-4 md:p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-black text-primary">طلب #{request.ref_no}</span><h2 className="mt-1 text-base font-black">{request.title}</h2><p className="mt-1 text-xs text-muted-foreground">{request.service_catalog?.name_ar ?? request.service_code}</p></div><StatusBadge status={request.status} /></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-muted-foreground">{request.description}</p><div className="mt-4 grid gap-2 border-t pt-3 text-xs text-muted-foreground md:grid-cols-3"><span><MapPin className="ml-1 inline h-4 w-4 text-primary" />{address?.city} · {address?.district}</span><span><CalendarClock className="ml-1 inline h-4 w-4 text-primary" />{request.service_timing_mode === "asap" ? "في أسرع وقت" : `${request.scheduled_date} · ${request.scheduled_time}`}</span><span>{request.status === "completed" ? <CheckCircle2 className="ml-1 inline h-4 w-4 text-primary" /> : <Clock3 className="ml-1 inline h-4 w-4 text-primary" />}آخر تحديث: {new Date(request.updated_at).toLocaleString("ar-SA")}</span></div>
        {request.status === "new" && offers.length > 0 && <div className="mt-4 rounded-2xl bg-[#f7f5ee] p-3"><p className="text-[10px] font-black">العروض المتاحة ({offers.length})</p><div className="mt-2 grid gap-2 md:grid-cols-2">{offers.map((offer: any) => <div key={offer.id} className="rounded-xl border bg-white p-3"><div className="flex items-center justify-between"><strong className="text-[10px]">{offer.maintenance_providers?.name}</strong><span className="text-[9px] text-amber-600"><Star className="inline h-3 w-3 fill-current" /> {offer.maintenance_providers?.rating ?? "جديد"}</span></div><strong className="mt-2 block text-lg text-primary">{Number(offer.offered_price).toLocaleString("ar-SA")} ر.س</strong><p className="mt-1 text-[8px] text-muted-foreground">قبل ضريبة القيمة المضافة</p>{offer.notes && <p className="mt-2 text-[9px] leading-5 text-muted-foreground">{offer.notes}</p>}<Button disabled={command.isPending} onClick={() => command.mutate({ kind: "accept", requestId: request.id, value: offer.id })} className="mt-3 w-full rounded-xl">اختيار هذا المزود</Button></div>)}</div></div>}
        {request.status === "waiting_confirmation" && <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "confirm", requestId: request.id })} className="mt-4 w-full rounded-xl"><CheckCircle2 className="ml-2 h-4 w-4" />تأكيد جودة التنفيذ وإصدار الفاتورة</Button>}
        {request.status === "waiting_payment" && invoice && <div className="mt-4 rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black">الفاتورة</p><small className="text-[8px] text-muted-foreground">الأساس {invoice.base_amount} + الضريبة {invoice.vat_amount}</small></div><strong className="text-xl text-primary">{Number(invoice.amount).toLocaleString("ar-SA")} ر.س</strong></div>{invoice.status === "pending_payment" ? <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "pay", requestId: request.id })} className="mt-3 w-full rounded-xl"><Banknote className="ml-2 h-4 w-4" />تسجيل الدفع النقدي</Button> : <p className="mt-3 rounded-xl bg-amber-100 p-3 text-center text-[9px] font-black text-amber-800">تم تسجيل الدفع، بانتظار تأكيد المزود</p>}</div>}
        {request.status === "completed" && request.after_service_policy !== "none" && <div className="mt-4 rounded-2xl border border-dashed p-3"><p className="flex items-center gap-2 text-[10px] font-black"><ShieldCheck className="h-4 w-4 text-primary" />خدمة ما بعد التنفيذ: {request.after_service_policy}</p><Textarea rows={2} value={warrantyReason[request.id] ?? ""} onChange={(event) => setWarrantyReason((current) => ({ ...current, [request.id]: event.target.value }))} placeholder="اشرح المشكلة التي ظهرت بعد التنفيذ" className="mt-2" /><Button variant="outline" disabled={(warrantyReason[request.id]?.trim().length ?? 0) < 5 || command.isPending} onClick={() => command.mutate({ kind: "warranty", requestId: request.id, value: warrantyReason[request.id] })} className="mt-2 w-full rounded-xl">فتح طلب الضمان</Button></div>}
        {request.status === "warranty_waiting_confirmation" && <Button disabled={command.isPending} onClick={() => command.mutate({ kind: "resolve", requestId: request.id })} className="mt-4 w-full rounded-xl">تأكيد حل مشكلة الضمان</Button>}
        {canCustomerReschedule(request.status) && <div className="mt-4 border-t pt-4"><button type="button" onClick={() => { setManageRequestId((current) => current === request.id ? null : request.id); setScheduleDate(request.scheduled_date ?? ""); setScheduleTime(request.scheduled_time?.slice(0, 5) ?? ""); setChangeReason(""); }} className="min-h-11 w-full rounded-xl border text-sm font-black text-muted-foreground">إدارة الموعد والطلب</button>{manageRequestId === request.id && <div className="mt-3 rounded-2xl bg-muted/60 p-4"><h3 className="text-sm font-black">إعادة الجدولة</h3><div className="mt-3 grid grid-cols-2 gap-2"><input aria-label="تاريخ الموعد الجديد" type="date" min={new Date().toISOString().slice(0, 10)} value={scheduleDate} onChange={(event) => setScheduleDate(event.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm" /><input aria-label="وقت الموعد الجديد" type="time" value={scheduleTime} onChange={(event) => setScheduleTime(event.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm" /></div><Textarea rows={2} maxLength={500} value={changeReason} onChange={(event) => setChangeReason(event.target.value)} placeholder={canCustomerCancel(request.status) ? "سبب التغيير أو الإلغاء" : "سبب تغيير الموعد ليصل إلى المزود"} className="mt-2 bg-white" /><Button variant="outline" disabled={command.isPending || !scheduleDate || !scheduleTime} onClick={() => command.mutate({ kind: "reschedule", requestId: request.id, value: changeReason })} className="mt-2 w-full"><CalendarClock className="ml-2 h-4 w-4" />حفظ الموعد الجديد</Button>{canCustomerCancel(request.status) ? <Button variant="destructive" disabled={command.isPending || changeReason.trim().length < 3} onClick={() => command.mutate({ kind: "cancel", requestId: request.id, value: changeReason })} className="mt-2 w-full"><XCircle className="ml-2 h-4 w-4" />تأكيد إلغاء الطلب</Button> : <p className="mt-3 text-xs leading-6 text-muted-foreground">لإلغاء طلب بعد اختيار المزود تواصل مع الدعم؛ هذا يمنع الإلغاء غير المقصود بعد حجز وقت المزود.</p>}</div>}</div>}
      </article>;
    })}</div>}
  </ServiceShell>;
}
