import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Banknote, BriefcaseBusiness, Clock3, FileCheck2, Loader2, MapPin, ShieldCheck, Upload, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { ServiceShell } from "@/components/service/ServiceShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { SERVICE_CATALOG } from "@/lib/serviceCatalog";
import { cn } from "@/lib/utils";

type DocumentType = "id_card" | "commercial_registration" | "bank_iban";
const DOCUMENT_LABELS: Record<DocumentType, string> = { id_card: "الهوية الوطنية", commercial_registration: "السجل التجاري", bank_iban: "شهادة الآيبان" };
const NEXT_STATUS: Record<string, { target: string; label: string }> = {
  accepted: { target: "arrived", label: "تأكيد الوصول" }, arrived: { target: "in_progress", label: "بدء العمل" },
  in_progress: { target: "waiting_confirmation", label: "إنهاء العمل وطلب التأكيد" },
  warranty_requested: { target: "warranty_in_progress", label: "بدء معالجة الضمان" },
  warranty_in_progress: { target: "warranty_waiting_confirmation", label: "إنهاء معالجة الضمان" },
};

export function ProviderPortalPage() {
  const { user, refreshProfile } = useAuth();
  const client = useQueryClient();
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [iban, setIban] = useState("");
  const [kind, setKind] = useState<"individual" | "company">("individual"); const [services, setServices] = useState<string[]>([]);
  const [quote, setQuote] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({});

  const providerQuery = useQuery({ queryKey: ["provider-self", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await (supabase as any).from("maintenance_providers").select("*").eq("user_id", user!.id).maybeSingle(); if (error) throw error; return data as any; } });
  const documentsQuery = useQuery({ queryKey: ["provider-documents", user?.id], enabled: !!providerQuery.data, queryFn: async () => { const { data, error } = await (supabase as any).from("provider_documents").select("doc_type,status,review_notes,updated_at").eq("provider_user_id", user!.id); if (error) throw error; return data as any[]; } });
  const offersQuery = useQuery({ queryKey: ["provider-opportunities", user?.id], enabled: providerQuery.data?.verification_status === "approved", queryFn: async () => { const { data, error } = await (supabase as any).rpc("get_provider_opportunities"); if (error) throw error; return data as any[]; } });
  const activeRequestsQuery = useQuery({ queryKey: ["provider-active-requests", user?.id], enabled: providerQuery.data?.verification_status === "approved", queryFn: async () => { const { data, error } = await (supabase as any).from("maintenance_requests").select("id,ref_no,title,status,priority,offered_price,service_code,updated_at,provider_invoices(id,status,amount)").eq("provider_id", providerQuery.data.id).not("status", "in", '("completed","cancelled","new")').order("updated_at", { ascending: false }); if (error) throw error; return data as any[]; } });
  const settlementsQuery = useQuery({ queryKey: ["provider-settlements", user?.id], enabled: !!providerQuery.data, queryFn: async () => { const { data, error } = await (supabase as any).from("provider_settlements").select("id,ref_no,total_amount,status,transactions_count,created_at").eq("provider_user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data as any[]; } });

  useEffect(() => {
    if (!user) return;
    const channel = supabase.channel(`provider-work-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "provider_offers", filter: `provider_user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["provider-opportunities", user.id] })).on("postgres_changes", { event: "*", schema: "public", table: "provider_settlements", filter: `provider_user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["provider-settlements", user.id] })).subscribe();
    return () => { void supabase.removeChannel(channel); };
  }, [user, client]);

  const register = useMutation({ mutationFn: async (event: FormEvent) => { event.preventDefault(); if (!user || services.length === 0) throw new Error("اختر خدمة واحدة على الأقل"); const category = SERVICE_CATALOG.find((item) => item.code === services[0])?.legacyCategory ?? "general"; const { data, error } = await (supabase as any).from("maintenance_providers").insert({ user_id: user.id, name: name.trim(), phone: phone.trim() || null, iban: iban.trim(), business_kind: kind, category, verification_status: "pending", is_active: false }).select("id").single(); if (error) throw error; const selected = await (supabase as any).from("provider_service_catalog").insert(services.map((service_code) => ({ provider_id: data.id, service_code }))); if (selected.error) throw selected.error; }, onSuccess: async () => { await Promise.all([providerQuery.refetch(), refreshProfile()]); toast.success("تم إنشاء ملف المزود؛ أكمل وثائق التحقق"); }, onError: (error: Error) => toast.error(error.message) });

  const uploadDocument = async (type: DocumentType, event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file || !user) return;
    const extension = file.name.split(".").pop()?.toLowerCase() || "bin"; const path = `${user.id}/${type}/${crypto.randomUUID()}.${extension}`;
    const uploaded = await supabase.storage.from("provider-documents").upload(path, file, { upsert: false });
    if (uploaded.error) { toast.error(uploaded.error.message); return; }
    const saved = await (supabase as any).rpc("register_provider_document", { doc_type_input: type, storage_path_input: path });
    if (saved.error) { await supabase.storage.from("provider-documents").remove([path]); toast.error(saved.error.message); return; }
    await documentsQuery.refetch(); toast.success(`تم رفع ${DOCUMENT_LABELS[type]}`);
  };
  const submitVerification = useMutation({ mutationFn: async () => { const { error } = await (supabase as any).rpc("submit_provider_verification"); if (error) throw error; }, onSuccess: async () => { await providerQuery.refetch(); toast.success("أُرسل الملف لمراجعة التوثيق"); }, onError: (error: Error) => toast.error(error.message === "required_documents_missing" ? "أكمل الوثائق المطلوبة أولًا" : error.message) });
  const respond = useMutation({ mutationFn: async ({ offerId, response }: { offerId: string; response: "quote" | "decline" }) => { const price = Number(quote[offerId]); const { error } = await (supabase as any).rpc("respond_to_provider_offer", { offer_id_input: offerId, response_input: response, offered_price_input: response === "quote" ? price : null, notes_input: notes[offerId] || null }); if (error) throw error; }, onSuccess: async () => { await offersQuery.refetch(); toast.success("تم تحديث العرض"); }, onError: (error: Error) => toast.error(error.message) });
  const transition = useMutation({ mutationFn: async ({ requestId, expected, target }: { requestId: string; expected: string; target: string }) => { const { error } = await (supabase as any).rpc("transition_maintenance_request", { request_id_input: requestId, expected_status_input: expected, target_status_input: target, idempotency_key_input: crypto.randomUUID(), payload_input: {} }); if (error) throw error; }, onSuccess: async () => { await activeRequestsQuery.refetch(); toast.success("تم تحديث حالة الطلب"); }, onError: (error: Error) => toast.error(error.message) });
  const confirmPayment = useMutation({ mutationFn: async (invoiceId: string) => { const { error } = await (supabase as any).rpc("confirm_maintenance_payment", { invoice_id_input: invoiceId }); if (error) throw error; }, onSuccess: async () => { await Promise.all([activeRequestsQuery.refetch(), settlementsQuery.refetch()]); toast.success("تم تأكيد الاستلام وإكمال الطلب"); }, onError: (error: Error) => toast.error(error.message) });
  const createSettlement = useMutation({ mutationFn: async () => { const { error } = await (supabase as any).rpc("create_provider_settlement"); if (error) throw error; }, onSuccess: async () => { await settlementsQuery.refetch(); toast.success("تم إنشاء التسوية"); }, onError: (error: Error) => toast.error(error.message === "no_unsettled_transactions" ? "لا توجد عمليات غير مسوّاة" : error.message) });

  if (providerQuery.isLoading) return <ServiceShell><div className="grid min-h-60 place-items-center"><Loader2 className="animate-spin text-primary" /></div></ServiceShell>;
  if (!providerQuery.data) return <ServiceShell><div className="mx-auto max-w-2xl"><p className="text-[10px] font-black text-primary">انضم إلى شبكة كافي سيرفس</p><h1 className="text-2xl font-black">تسجيل مزود خدمة</h1><p className="mt-1 text-[10px] leading-5 text-muted-foreground">تدفق كافي ٢ المحسّن: ملف أعمال، خدمات دقيقة، توثيق، ثم مراجعة قبل استقبال الطلبات.</p><form onSubmit={(event) => register.mutate(event)} className="mt-6 space-y-4 rounded-[28px] border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><div><label className="text-[10px] font-black">اسم المزود أو المنشأة</label><Input required minLength={3} value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-12 rounded-xl text-base" /></div><div><label className="text-[10px] font-black">رقم التواصل</label><Input dir="ltr" value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 h-12 rounded-xl text-base" /></div></div><div><label className="text-[10px] font-black">الآيبان</label><Input required dir="ltr" value={iban} onChange={(event) => setIban(event.target.value.toUpperCase())} placeholder="SA..." className="mt-2 h-12 rounded-xl text-base" /></div><div><label className="text-[10px] font-black">نوع النشاط</label><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => setKind("individual")} className={cn("h-11 rounded-xl text-[10px] font-black", kind === "individual" ? "bg-primary text-white" : "bg-secondary")}>فرد</button><button type="button" onClick={() => setKind("company")} className={cn("h-11 rounded-xl text-[10px] font-black", kind === "company" ? "bg-primary text-white" : "bg-secondary")}>منشأة</button></div></div><div><label className="text-[10px] font-black">الخدمات التي تقدمها</label><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-3">{SERVICE_CATALOG.map((service) => <button type="button" key={service.code} onClick={() => setServices((current) => current.includes(service.code) ? current.filter((code) => code !== service.code) : [...current, service.code])} className={cn("rounded-xl border px-2 py-2.5 text-[9px] font-bold", services.includes(service.code) ? "border-primary bg-primary/10 text-primary" : "border-border")}>{service.label}</button>)}</div></div><Button disabled={register.isPending || services.length === 0} className="h-12 w-full rounded-xl font-black">{register.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}إنشاء ملف المزود</Button></form></div></ServiceShell>;

  const provider = providerQuery.data; const documents = documentsQuery.data ?? []; const offers = offersQuery.data ?? []; const activeRequests = activeRequestsQuery.data ?? []; const settlements = settlementsQuery.data ?? [];
  const requiredDocs: DocumentType[] = provider.business_kind === "company" ? ["id_card", "commercial_registration", "bank_iban"] : ["id_card", "bank_iban"];
  return <ServiceShell><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black text-primary">بوابة المزود</p><h1 className="text-2xl font-black">مرحبًا، {provider.name}</h1><p className="mt-1 text-[10px] text-muted-foreground">التوثيق والتشغيل والضمان والتسويات في مساحة واحدة.</p></div><span className={cn("rounded-full px-3 py-1.5 text-[9px] font-black", provider.verification_status === "approved" ? "bg-primary/10 text-primary" : "bg-amber-100 text-amber-700")}>{provider.verification_status === "approved" ? "موثق ونشط" : provider.verification_status}</span></div>
    <div className="mt-6 grid grid-cols-3 gap-3"><article className="rounded-2xl border bg-white p-4"><BriefcaseBusiness className="h-5 w-5 text-primary" /><strong className="mt-3 block text-2xl">{offers.filter((offer) => offer.offer_status === "pending").length}</strong><small className="text-[9px] text-muted-foreground">فرص جديدة</small></article><article className="rounded-2xl border bg-white p-4"><BadgeCheck className="h-5 w-5 text-primary" /><strong className="mt-3 block text-2xl">{provider.rating ?? "—"}</strong><small className="text-[9px] text-muted-foreground">التقييم</small></article><article className="rounded-2xl border bg-white p-4"><WalletCards className="h-5 w-5 text-primary" /><strong className="mt-3 block text-2xl">{settlements.length}</strong><small className="text-[9px] text-muted-foreground">التسويات</small></article></div>
    {provider.verification_status !== "approved" && <section className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-amber-700" /><div><p className="text-[11px] font-black text-amber-800">أكمل التوثيق لتفعيل استقبال الطلبات</p><p className="mt-1 text-[9px] leading-5 text-amber-700">الوثائق خاصة، وتظهر لك ولمراجع الامتثال فقط.</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-3">{requiredDocs.map((type) => { const doc = documents.find((item) => item.doc_type === type); return <label key={type} className="cursor-pointer rounded-xl border border-amber-200 bg-white p-3"><span className="flex items-center gap-2 text-[10px] font-black"><Upload className="h-4 w-4" />{DOCUMENT_LABELS[type]}</span><small className="mt-2 block text-[8px] text-muted-foreground">{doc ? `مرفوع · ${doc.status}` : "PDF أو صورة، حتى 10MB"}</small><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="hidden" onChange={(event) => void uploadDocument(type, event)} /></label>; })}</div><Button disabled={submitVerification.isPending || requiredDocs.some((type) => !documents.some((doc) => doc.doc_type === type))} onClick={() => submitVerification.mutate()} className="mt-4 w-full rounded-xl"><FileCheck2 className="ml-2 h-4 w-4" />إرسال الملف للمراجعة</Button></section>}
    {provider.verification_status === "approved" && <><section className="mt-7"><h2 className="text-base font-black">فرص الطلبات</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{offers.filter((offer) => offer.offer_status === "pending").length === 0 ? <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-[10px] text-muted-foreground"><Clock3 className="mx-auto mb-2 h-6 w-6" />لا توجد فرص موجهة لك الآن</div> : offers.filter((offer) => offer.offer_status === "pending").map((offer) => <article key={offer.offer_id} className="rounded-2xl border bg-white p-4"><span className="text-[9px] font-black text-primary">طلب #{offer.ref_no} · {offer.service_name_ar}</span><h3 className="mt-1 text-sm font-black">{offer.title}</h3><p className="mt-2 text-[9px] leading-5 text-muted-foreground">{offer.description}</p><p className="mt-2 text-[9px]"><MapPin className="ml-1 inline h-3.5 w-3.5 text-primary" />{offer.city} · {offer.district}</p>{offer.quoted_at ? <div className="mt-3 rounded-xl bg-primary/10 p-3 text-[10px] font-black text-primary">تم إرسال عرضك: {Number(offer.offered_price).toLocaleString("ar-SA")} ر.س</div> : <div className="mt-3 grid gap-2"><Input type="number" min="1" placeholder="سعر العرض قبل الضريبة" value={quote[offer.offer_id] ?? ""} onChange={(event) => setQuote((current) => ({ ...current, [offer.offer_id]: event.target.value }))} /><Textarea rows={2} placeholder="تفاصيل العرض والمدة المتوقعة" value={notes[offer.offer_id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [offer.offer_id]: event.target.value }))} /><div className="flex gap-2"><Button disabled={respond.isPending || Number(quote[offer.offer_id]) <= 0} onClick={() => respond.mutate({ offerId: offer.offer_id, response: "quote" })} className="flex-1">إرسال العرض</Button><Button variant="outline" onClick={() => respond.mutate({ offerId: offer.offer_id, response: "decline" })}>اعتذار</Button></div></div>}</article>)}</div></section>
    <section className="mt-7"><h2 className="text-base font-black">الأعمال الحالية</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{activeRequests.length === 0 ? <p className="rounded-2xl border border-dashed bg-white p-8 text-center text-[10px] text-muted-foreground">لا توجد أعمال مسندة</p> : activeRequests.map((request) => { const next = NEXT_STATUS[request.status]; const invoice = request.provider_invoices?.[0]; return <article key={request.id} className="rounded-2xl border bg-white p-4"><span className="text-[9px] font-black text-primary">طلب #{request.ref_no}</span><h3 className="mt-1 font-black">{request.title}</h3><p className="mt-2 text-[9px] text-muted-foreground">الحالة: {request.status} · السعر: {request.offered_price ?? "—"} ر.س</p>{next && <Button onClick={() => transition.mutate({ requestId: request.id, expected: request.status, target: next.target })} className="mt-3 w-full rounded-xl">{next.label}</Button>}{invoice?.status === "payment_submitted" && <Button onClick={() => confirmPayment.mutate(invoice.id)} className="mt-3 w-full rounded-xl"><Banknote className="ml-2 h-4 w-4" />تأكيد استلام {invoice.amount} ر.س</Button>}</article>; })}</div></section>
    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="text-base font-black">التسويات</h2><Button variant="outline" size="sm" onClick={() => createSettlement.mutate()}>إنشاء تسوية مستحقة</Button></div><div className="mt-3 space-y-2">{settlements.length === 0 ? <p className="rounded-2xl border border-dashed bg-white p-7 text-center text-[10px] text-muted-foreground">لا توجد تسويات</p> : settlements.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl border bg-white p-4"><div><strong className="text-[11px]">تسوية #{item.ref_no}</strong><p className="mt-1 text-[9px] text-muted-foreground">{item.transactions_count} عمليات · {item.status}</p></div><strong className="text-primary">{Number(item.total_amount).toLocaleString("ar-SA")} ر.س</strong></div>)}</div></section></>}
  </ServiceShell>;
}
