import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Banknote, BriefcaseBusiness, Clock3, FileCheck2, Loader2, MapPin, ShieldCheck, Upload, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { ServiceShell } from "@/components/service/ServiceShell";
import { EmptyState, MetricCard, PageHeading, SectionHeading, StatusBadge } from "@/components/service/ServiceUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { SERVICE_CATALOG } from "@/lib/serviceCatalog";
import { formatMoney } from "@/lib/servicePresentation";
import { getProviderNextTransition } from "@/lib/maintenanceWorkflow";
import { cn } from "@/lib/utils";

type DocumentType = "id_card" | "commercial_registration" | "bank_iban";
const DOCUMENT_LABELS: Record<DocumentType, string> = { id_card: "الهوية الوطنية", commercial_registration: "السجل التجاري", bank_iban: "شهادة الآيبان" };
export function ProviderPortalPage() {
  const { user, refreshProfile } = useAuth();
  const client = useQueryClient();
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [iban, setIban] = useState("");
  const [kind, setKind] = useState<"individual" | "company">("individual"); const [services, setServices] = useState<string[]>([]);
  const [quote, setQuote] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({});
  const [uploadingSettlement, setUploadingSettlement] = useState<string | null>(null);

  const providerQuery = useQuery({ queryKey: ["provider-self", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await (supabase as any).from("maintenance_providers").select("*").eq("user_id", user!.id).maybeSingle(); if (error) throw error; return data as any; } });
  const documentsQuery = useQuery({ queryKey: ["provider-documents", user?.id], enabled: !!providerQuery.data, queryFn: async () => { const { data, error } = await (supabase as any).from("provider_documents").select("doc_type,status,review_notes,updated_at").eq("provider_user_id", user!.id); if (error) throw error; return data as any[]; } });
  const offersQuery = useQuery({ queryKey: ["provider-opportunities", user?.id], enabled: providerQuery.data?.verification_status === "approved", queryFn: async () => { const { data, error } = await (supabase as any).rpc("get_provider_opportunities"); if (error) throw error; return data as any[]; } });
  const activeRequestsQuery = useQuery({ queryKey: ["provider-active-requests", user?.id], enabled: providerQuery.data?.verification_status === "approved", queryFn: async () => { const { data, error } = await (supabase as any).from("maintenance_requests").select("id,ref_no,title,status,priority,offered_price,service_code,updated_at,provider_invoices(id,status,amount)").eq("provider_id", providerQuery.data.id).not("status", "in", '("completed","cancelled","new")').order("updated_at", { ascending: false }); if (error) throw error; return data as any[]; } });
  const settlementsQuery = useQuery({ queryKey: ["provider-settlements", user?.id], enabled: !!providerQuery.data, queryFn: async () => { const { data, error } = await (supabase as any).from("provider_settlements").select("id,ref_no,total_amount,status,transactions_count,receipt_storage_path,submitted_at,confirmed_at,created_at").eq("provider_user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data as any[]; } });

  useEffect(() => {
    if (!user) return;
    const channel = supabase.channel(`provider-work-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "provider_offers", filter: `provider_user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["provider-opportunities", user.id] })).on("postgres_changes", { event: "*", schema: "public", table: "provider_settlements", filter: `provider_user_id=eq.${user.id}` }, () => client.invalidateQueries({ queryKey: ["provider-settlements", user.id] })).subscribe();
    return () => { void supabase.removeChannel(channel); };
  }, [user, client]);

  const register = useMutation({ mutationFn: async (event: FormEvent) => { event.preventDefault(); if (!user || services.length === 0) throw new Error("اختر خدمة واحدة على الأقل"); const { error } = await (supabase as any).rpc("register_maintenance_provider", { name_input: name.trim(), phone_input: phone.trim() || null, iban_input: iban.trim(), business_kind_input: kind, service_codes_input: services }); if (error) throw error; }, onSuccess: async () => { await Promise.all([providerQuery.refetch(), refreshProfile()]); toast.success("تم إنشاء ملف المزود؛ أكمل وثائق التحقق"); }, onError: (error: Error) => toast.error(error.message === "valid_saudi_iban_required" ? "تحقق من الآيبان السعودي؛ يجب أن يبدأ بـ SA ويتكون من 24 خانة" : error.message) });

  const uploadDocument = async (type: DocumentType, event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file || !user) return;
    const extension = file.name.split(".").pop()?.toLowerCase() || "bin"; const path = `${user.id}/${type}/${crypto.randomUUID()}.${extension}`;
    const uploaded = await supabase.storage.from("provider-documents").upload(path, file, { upsert: false });
    if (uploaded.error) { toast.error(uploaded.error.message); return; }
    const saved = await (supabase as any).rpc("register_provider_document", { doc_type_input: type, storage_path_input: path });
    if (saved.error) { await supabase.storage.from("provider-documents").remove([path]); toast.error(saved.error.message); return; }
    await documentsQuery.refetch(); toast.success(`تم رفع ${DOCUMENT_LABELS[type]}`);
  };
  const submitVerification = useMutation({ mutationFn: async () => { const { error } = await (supabase as any).rpc("submit_provider_verification"); if (error) throw error; }, onSuccess: async () => { await providerQuery.refetch(); toast.success("أُرسل الملف لمراجعة التوثيق"); }, onError: (error: Error) => toast.error(error.message === "required_documents_missing" ? "أكمل الوثائق المطلوبة أولًا" : error.message) });
  const respond = useMutation({ mutationFn: async ({ offerId, response }: { offerId: string; response: "quote" | "decline" }) => { const price = Number(quote[offerId]); const { error } = await (supabase as any).rpc("respond_to_provider_offer", { offer_id_input: offerId, response_input: response, offered_price_input: response === "quote" ? price : null, notes_input: notes[offerId] || null }); if (error) throw error; }, onSuccess: async () => { await offersQuery.refetch(); toast.success("تم تحديث العرض"); }, onError: (error: Error) => toast.error(error.message) });
  const transition = useMutation({ mutationFn: async ({ requestId, expected, target }: { requestId: string; expected: string; target: string }) => { const { error } = await (supabase as any).rpc("transition_maintenance_request", { request_id_input: requestId, expected_status_input: expected, target_status_input: target, idempotency_key_input: crypto.randomUUID(), payload_input: {} }); if (error) throw error; }, onSuccess: async () => { await activeRequestsQuery.refetch(); toast.success("تم تحديث حالة الطلب"); }, onError: (error: Error) => toast.error(error.message) });
  const confirmPayment = useMutation({ mutationFn: async (invoiceId: string) => { const { error } = await (supabase as any).rpc("confirm_maintenance_payment", { invoice_id_input: invoiceId }); if (error) throw error; }, onSuccess: async () => { await Promise.all([activeRequestsQuery.refetch(), settlementsQuery.refetch()]); toast.success("تم تأكيد الاستلام وإكمال الطلب"); }, onError: (error: Error) => toast.error(error.message) });
  const createSettlement = useMutation({ mutationFn: async () => { const { error } = await (supabase as any).rpc("create_provider_settlement"); if (error) throw error; }, onSuccess: async () => { await settlementsQuery.refetch(); toast.success("تم إنشاء التسوية"); }, onError: (error: Error) => toast.error(error.message === "no_unsettled_transactions" ? "لا توجد عمليات غير مسوّاة" : error.message) });
  const uploadSettlementReceipt = async (settlementId: string, event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = "";
    if (!file || !user) return;
    if (!["image/jpeg", "image/png", "image/webp", "application/pdf"].includes(file.type) || file.size > 10 * 1024 * 1024) { toast.error("الإيصال يجب أن يكون PDF أو صورة وبحجم لا يتجاوز 10MB"); return; }
    setUploadingSettlement(settlementId);
    const extension = file.name.split(".").pop()?.toLowerCase() || "bin";
    const path = `${user.id}/${settlementId}/${crypto.randomUUID()}.${extension}`;
    const uploaded = await supabase.storage.from("settlement-receipts").upload(path, file, { contentType: file.type, upsert: false });
    if (uploaded.error) { setUploadingSettlement(null); toast.error(uploaded.error.message); return; }
    const saved = await (supabase as any).rpc("submit_provider_settlement_receipt", { settlement_id_input: settlementId, receipt_path_input: path });
    if (saved.error) { await supabase.storage.from("settlement-receipts").remove([path]); setUploadingSettlement(null); toast.error(saved.error.message); return; }
    await settlementsQuery.refetch(); setUploadingSettlement(null); toast.success("تم إرسال إيصال التسوية للمراجعة");
  };

  if (providerQuery.isLoading) return <ServiceShell><div className="grid min-h-60 place-items-center"><Loader2 className="animate-spin text-primary" /></div></ServiceShell>;
  if (!providerQuery.data) return <ServiceShell><div className="mx-auto max-w-2xl"><PageHeading eyebrow="انضم إلى شبكة كافي سيرفس" title="تسجيل مزود خدمة" description="أنشئ ملف أعمالك، حدد خدماتك بدقة، ثم أكمل التوثيق قبل استقبال الطلبات." /><form onSubmit={(event) => register.mutate(event)} className="service-panel mt-6 space-y-5 p-5 md:p-6"><div className="grid gap-4 md:grid-cols-2"><div><label className="text-sm font-black">اسم المزود أو المنشأة</label><Input required minLength={3} value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-12 rounded-xl text-base" /></div><div><label className="text-sm font-black">رقم التواصل</label><Input dir="ltr" inputMode="tel" value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 h-12 rounded-xl text-base" /></div></div><div><label className="text-sm font-black">الآيبان السعودي</label><Input required dir="ltr" value={iban} onChange={(event) => setIban(event.target.value.replace(/\s/g, "").toUpperCase())} minLength={24} maxLength={24} placeholder="SA0000000000000000000000" className="mt-2 h-12 rounded-xl text-base" /><p className="mt-1 text-xs text-muted-foreground">24 خانة ويبدأ بـ SA. يستخدم للتسويات بعد التوثيق.</p></div><div><label className="text-sm font-black">نوع النشاط</label><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => setKind("individual")} className={cn("min-h-11 rounded-xl text-sm font-black", kind === "individual" ? "bg-primary text-white" : "bg-secondary")}>فرد</button><button type="button" onClick={() => setKind("company")} className={cn("min-h-11 rounded-xl text-sm font-black", kind === "company" ? "bg-primary text-white" : "bg-secondary")}>منشأة</button></div></div><div><div className="flex items-center justify-between"><label className="text-sm font-black">الخدمات التي تقدمها</label><span className="text-xs font-bold text-primary">{services.length} محددة</span></div><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-3">{SERVICE_CATALOG.map((service) => <button type="button" key={service.code} aria-pressed={services.includes(service.code)} onClick={() => setServices((current) => current.includes(service.code) ? current.filter((code) => code !== service.code) : [...current, service.code])} className={cn("min-h-11 rounded-xl border px-3 py-2.5 text-sm font-bold", services.includes(service.code) ? "border-primary bg-primary/10 text-primary" : "border-border")}>{service.label}</button>)}</div></div><Button disabled={register.isPending || services.length === 0 || iban.length !== 24} className="h-12 w-full rounded-xl font-black">{register.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}إنشاء ملف المزود</Button></form></div></ServiceShell>;

  const provider = providerQuery.data; const documents = documentsQuery.data ?? []; const offers = offersQuery.data ?? []; const activeRequests = activeRequestsQuery.data ?? []; const settlements = settlementsQuery.data ?? [];
  const requiredDocs: DocumentType[] = provider.business_kind === "company" ? ["id_card", "commercial_registration", "bank_iban"] : ["id_card", "bank_iban"];
  return <ServiceShell><PageHeading eyebrow="بوابة المزود" title={`مرحبًا، ${provider.name}`} description="التوثيق والفرص والأعمال والضمان والتسويات في مساحة تشغيل واحدة." action={<StatusBadge status={provider.verification_status} />} />
    <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-3"><MetricCard icon={BriefcaseBusiness} value={offers.filter((offer) => offer.offer_status === "pending").length} label="فرص جديدة" /><MetricCard icon={BadgeCheck} value={provider.rating ?? "—"} label="التقييم" /><MetricCard icon={WalletCards} value={settlements.length} label="التسويات" /></div>
    {provider.verification_status !== "approved" && <section className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-4"><div className="flex items-start gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-amber-700" /><div><p className="text-[11px] font-black text-amber-800">أكمل التوثيق لتفعيل استقبال الطلبات</p><p className="mt-1 text-[9px] leading-5 text-amber-700">الوثائق خاصة، وتظهر لك ولمراجع الامتثال فقط.</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-3">{requiredDocs.map((type) => { const doc = documents.find((item) => item.doc_type === type); return <label key={type} className="cursor-pointer rounded-xl border border-amber-200 bg-white p-3"><span className="flex items-center gap-2 text-[10px] font-black"><Upload className="h-4 w-4" />{DOCUMENT_LABELS[type]}</span><small className="mt-2 block text-[8px] text-muted-foreground">{doc ? `مرفوع · ${doc.status}` : "PDF أو صورة، حتى 10MB"}</small><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="hidden" onChange={(event) => void uploadDocument(type, event)} /></label>; })}</div><Button disabled={submitVerification.isPending || requiredDocs.some((type) => !documents.some((doc) => doc.doc_type === type))} onClick={() => submitVerification.mutate()} className="mt-4 w-full rounded-xl"><FileCheck2 className="ml-2 h-4 w-4" />إرسال الملف للمراجعة</Button></section>}
    {provider.verification_status === "approved" && <><section className="mt-8"><SectionHeading title="فرص الطلبات" description="الفرص المطابقة لخدماتك، مرتبة حسب الأولوية" /><div className="mt-4 grid gap-3 md:grid-cols-2">{offers.filter((offer) => offer.offer_status === "pending").length === 0 ? <EmptyState icon={Clock3} title="لا توجد فرص جديدة الآن" description="ستظهر هنا الطلبات المطابقة لخدماتك فور توجيهها إليك." /> : offers.filter((offer) => offer.offer_status === "pending").map((offer) => <article key={offer.offer_id} className="service-panel p-4"><span className="text-xs font-black text-primary">طلب #{offer.ref_no} · {offer.service_name_ar}</span><h3 className="mt-1 text-base font-black">{offer.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{offer.description}</p><p className="mt-2 text-xs"><MapPin className="ml-1 inline h-4 w-4 text-primary" />{offer.city} · {offer.district}</p>{offer.quoted_at ? <div className="mt-3 rounded-xl bg-primary/10 p-3 text-sm font-black text-primary">تم إرسال عرضك: {formatMoney(offer.offered_price)}</div> : <div className="mt-3 grid gap-2"><Input type="number" min="1" placeholder="سعر العرض قبل الضريبة" value={quote[offer.offer_id] ?? ""} onChange={(event) => setQuote((current) => ({ ...current, [offer.offer_id]: event.target.value }))} /><Textarea rows={2} placeholder="اشرح ما يشمله السعر والمدة المتوقعة" value={notes[offer.offer_id] ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [offer.offer_id]: event.target.value }))} /><div className="flex gap-2"><Button disabled={respond.isPending || Number(quote[offer.offer_id]) <= 0} onClick={() => respond.mutate({ offerId: offer.offer_id, response: "quote" })} className="flex-1">إرسال العرض</Button><Button variant="outline" onClick={() => respond.mutate({ offerId: offer.offer_id, response: "decline" })}>اعتذار</Button></div></div>}</article>)}</div></section>
    <section className="mt-7"><SectionHeading title="الأعمال الحالية" description="نفّذ كل مرحلة بالترتيب لتبقى حالة العميل دقيقة" /><div className="mt-3 grid gap-3 md:grid-cols-2">{activeRequests.length === 0 ? <EmptyState icon={BriefcaseBusiness} title="لا توجد أعمال مسندة" /> : activeRequests.map((request) => { const next = getProviderNextTransition(request.status); const invoice = request.provider_invoices?.[0]; return <article key={request.id} className="service-panel p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-black text-primary">طلب #{request.ref_no}</span><h3 className="mt-1 font-black">{request.title}</h3></div><StatusBadge status={request.status} /></div><p className="mt-3 text-sm text-muted-foreground">السعر المتفق عليه: <strong className="text-foreground">{formatMoney(request.offered_price)}</strong></p>{next && <Button disabled={transition.isPending} onClick={() => transition.mutate({ requestId: request.id, expected: request.status, target: next.target })} className="mt-3 w-full rounded-xl">{next.label}</Button>}{invoice?.status === "payment_submitted" && <Button disabled={confirmPayment.isPending} onClick={() => confirmPayment.mutate(invoice.id)} className="mt-3 w-full rounded-xl"><Banknote className="ml-2 h-4 w-4" />تأكيد استلام {formatMoney(invoice.amount)}</Button>}</article>; })}</div></section>
    <section className="mt-8"><SectionHeading title="التسويات" description="اجمع رسوم المنصة، ارفع الإيصال، ثم تابع الاعتماد" action={<Button variant="outline" size="sm" disabled={createSettlement.isPending} onClick={() => createSettlement.mutate()}>إنشاء تسوية مستحقة</Button>} /><div className="mt-4 space-y-3">{settlements.length === 0 ? <EmptyState icon={WalletCards} title="لا توجد تسويات" description="عند اكتمال عمليات مالية غير مسوّاة يمكنك إنشاء دفعة مجمعة من هنا." /> : settlements.map((item) => <article key={item.id} className="service-panel flex flex-wrap items-center justify-between gap-4 p-4"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">تسوية #{item.ref_no}</strong><StatusBadge status={item.status} /></div><p className="mt-2 text-xs text-muted-foreground">{item.transactions_count} عمليات · أُنشئت {new Date(item.created_at).toLocaleDateString("ar-SA")}</p></div><div className="text-left"><strong className="block text-lg text-primary">{formatMoney(item.total_amount)}</strong>{item.status === "pending_payment" && <label className="mt-2 inline-flex min-h-10 cursor-pointer items-center gap-2 rounded-xl bg-primary px-3 text-xs font-black text-white"><Upload className="h-4 w-4" />{uploadingSettlement === item.id ? "جارٍ الرفع…" : "رفع إيصال الدفع"}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="hidden" disabled={uploadingSettlement === item.id} onChange={(event) => void uploadSettlementReceipt(item.id, event)} /></label>}{item.status === "payment_submitted" && <p className="mt-2 text-xs font-bold text-amber-700">الإيصال تحت مراجعة المالية</p>}{item.status === "confirmed" && <p className="mt-2 text-xs font-bold text-primary">تم اعتماد التسوية</p>}</div></article>)}</div></section></>}
  </ServiceShell>;
}
