import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AlertTriangle, BadgeCheck, Banknote, Clock3, ShieldCheck, Users, Wrench } from "lucide-react";
import { toast } from "sonner";
import { ServiceShell } from "@/components/service/ServiceShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";

export function ServiceOwnerPage() {
  const { profile } = useAuth(); const [reviewNotes, setReviewNotes] = useState<Record<string, string>>({});
  const isPlatform = !!profile?.role?.startsWith("platform_") || ["compliance_reviewer", "finance_operator", "support_agent"].includes(profile?.role ?? "");
  const dashboard = useQuery({ queryKey: ["service-owner-dashboard"], enabled: isPlatform, queryFn: async () => {
    const [requests, providers, settlements] = await Promise.all([
      (supabase as any).from("maintenance_requests").select("id,ref_no,title,status,priority,created_at,service_code").order("created_at", { ascending: false }).limit(50),
      (supabase as any).from("maintenance_providers").select("id,user_id,name,business_kind,verification_status,verification_notes,is_active,iban,created_at,provider_documents(doc_type,status,storage_path,review_notes)").order("created_at", { ascending: false }).limit(50),
      (supabase as any).from("provider_settlements").select("id,ref_no,total_amount,status,transactions_count,settlement_direction,receipt_storage_path,created_at,maintenance_providers(name)").order("created_at", { ascending: false }).limit(50),
    ]); const error = requests.error || providers.error || settlements.error; if (error) throw error;
    return { requests: requests.data as any[], providers: providers.data as any[], settlements: settlements.data as any[] };
  } });
  const review = useMutation({ mutationFn: async ({ providerId, decision }: { providerId: string; decision: "approved" | "needs_completion" | "suspended" }) => { const { error } = await (supabase as any).rpc("review_maintenance_provider", { provider_id_input: providerId, decision_input: decision, notes_input: reviewNotes[providerId] || null }); if (error) throw error; }, onSuccess: async () => { await dashboard.refetch(); toast.success("تم حفظ قرار التوثيق"); }, onError: (error: Error) => toast.error(error.message === "review_notes_required" ? "اكتب ملاحظة عند طلب الاستكمال أو الإيقاف" : error.message) });
  const confirmSettlement = useMutation({ mutationFn: async (settlementId: string) => { const { error } = await (supabase as any).rpc("confirm_provider_settlement", { settlement_id_input: settlementId, notes_input: null }); if (error) throw error; }, onSuccess: async () => { await dashboard.refetch(); toast.success("تم اعتماد التسوية وقفل عملياتها"); }, onError: (error: Error) => toast.error(error.message) });

  if (!isPlatform) return <ServiceShell><div className="mx-auto max-w-lg py-12 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-primary/10 text-primary"><ShieldCheck className="h-9 w-9" /></div><h1 className="mt-5 text-2xl font-black">مركز الأونر محمي</h1><p className="mt-2 text-[11px] leading-6 text-muted-foreground">لا تُمنح صلاحية الأونر من الواجهة. يجب إضافة عضوية منصة موثقة لهذا الحساب من قاعدة البيانات.</p></div></ServiceShell>;
  const data = dashboard.data ?? { requests: [], providers: [], settlements: [] };
  const pendingProviders = data.providers.filter((provider) => ["pending", "needs_completion", "under_review"].includes(provider.verification_status));
  const activeRequests = data.requests.filter((request) => !["completed", "cancelled", "warranty_resolved"].includes(request.status));
  const openSettlements = data.settlements.filter((settlement) => ["pending_payment", "payment_submitted"].includes(settlement.status));
  const metrics = [{ label: "طلبات نشطة", value: activeRequests.length, icon: Wrench }, { label: "مزودون للتوثيق", value: pendingProviders.length, icon: Users }, { label: "تسويات مفتوحة", value: openSettlements.length, icon: Banknote }, { label: "طلبات عاجلة", value: activeRequests.filter((request) => ["urgent", "emergency"].includes(request.priority)).length, icon: AlertTriangle }];
  return <ServiceShell><div><p className="text-[10px] font-black text-primary">مركز القرار والتشغيل</p><h1 className="text-2xl font-black">لوحة أونر كافي سيرفس</h1><p className="mt-1 text-[10px] text-muted-foreground">ضوابط كافي ٢ المحسّنة، بأرقام حقيقية ومسارات قرار قابلة للتدقيق.</p></div>
    <div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <article key={label} className="rounded-[20px] border bg-white p-4"><Icon className="h-5 w-5 text-primary" /><strong className="mt-3 block text-3xl">{value}</strong><small className="text-[9px] text-muted-foreground">{label}</small></article>)}</div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="overflow-hidden rounded-[24px] border bg-white"><div className="flex items-center justify-between border-b p-4"><div><p className="text-[9px] font-black text-primary">الأولوية الآن</p><h2 className="text-base font-black">طلبات تحتاج مراقبة</h2></div><Clock3 className="text-primary" /></div><div className="divide-y">{activeRequests.length === 0 ? <p className="p-8 text-center text-[10px] text-muted-foreground">لا توجد طلبات نشطة</p> : activeRequests.slice(0,8).map((request) => <div key={request.id} className="flex items-center justify-between gap-3 p-4"><div><span className="text-[8px] font-black text-primary">#{request.ref_no}</span><p className="mt-1 text-[11px] font-black">{request.title}</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[8px] font-black text-primary">{request.status}</span></div>)}</div></section>
      <section className="overflow-hidden rounded-[24px] border bg-white"><div className="flex items-center justify-between border-b p-4"><div><p className="text-[9px] font-black text-primary">الثقة أولًا</p><h2 className="text-base font-black">توثيق المزودين</h2></div><BadgeCheck className="text-primary" /></div><div className="divide-y">{pendingProviders.length === 0 ? <p className="p-8 text-center text-[10px] text-muted-foreground">لا توجد ملفات معلقة</p> : pendingProviders.slice(0,8).map((provider) => <div key={provider.id} className="p-4"><div className="flex items-center justify-between"><div><p className="text-[11px] font-black">{provider.name}</p><small className="text-[8px] text-muted-foreground">{provider.business_kind} · {provider.provider_documents?.length ?? 0} وثائق</small></div><span className="rounded-full bg-amber-100 px-2.5 py-1 text-[8px] font-black text-amber-700">{provider.verification_status}</span></div><Input value={reviewNotes[provider.id] ?? ""} onChange={(event) => setReviewNotes((current) => ({ ...current, [provider.id]: event.target.value }))} placeholder="ملاحظة المراجع عند طلب الاستكمال" className="mt-3 h-10 text-[10px]" /><div className="mt-2 flex gap-2"><Button size="sm" disabled={review.isPending || provider.verification_status !== "under_review"} onClick={() => review.mutate({ providerId: provider.id, decision: "approved" })} className="flex-1">اعتماد</Button><Button size="sm" variant="outline" disabled={review.isPending} onClick={() => review.mutate({ providerId: provider.id, decision: "needs_completion" })} className="flex-1">طلب استكمال</Button></div></div>)}</div></section></div>
    <section className="mt-5 overflow-hidden rounded-[24px] border bg-white"><div className="border-b p-4"><p className="text-[9px] font-black text-primary">الضبط المالي</p><h2 className="text-base font-black">التسويات</h2></div><div className="divide-y">{openSettlements.length === 0 ? <p className="p-8 text-center text-[10px] text-muted-foreground">لا توجد تسويات مفتوحة</p> : openSettlements.map((settlement) => <div key={settlement.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong className="text-[11px]">تسوية #{settlement.ref_no} · {settlement.maintenance_providers?.name}</strong><p className="mt-1 text-[9px] text-muted-foreground">{settlement.transactions_count} عمليات · {settlement.status}</p></div><div className="flex items-center gap-3"><strong className="text-primary">{Number(settlement.total_amount).toLocaleString("ar-SA")} ر.س</strong>{settlement.status === "payment_submitted" && <Button size="sm" disabled={confirmSettlement.isPending} onClick={() => confirmSettlement.mutate(settlement.id)}>اعتماد التسوية</Button>}</div></div>)}</div></section>
  </ServiceShell>;
}
